server:
  port: 8080
spring:
  application:
    name: "RetoBC"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  saldos:
    url: "https://rough-glitter-5481.getsandbox.com:443/balance"
  movimientos:
    url: "http://localhost:8080/dummy"
